# Generated by Django 5.0.6 on 2024-06-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='media/course_logo')),
                ('created_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Курсы на веб_сайт',
                'verbose_name_plural': 'Курсы на веб_сайт',
            },
        ),
    ]
