# Generated by Django 5.0.6 on 2024-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
