# Generated by Django 5.0.6 on 2024-06-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_time', models.CharField(max_length=77)),
                ('course_day', models.CharField(max_length=23)),
                ('course_duration', models.CharField(max_length=123)),
                ('is_teens', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Идет набор!'), (2, 'Набор зактрыт!'), (3, 'Скоро набор!')], default=3)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курс',
            },
        ),
    ]
